### ISSUE TITLE
New version broke the build

### ISSUE THREAD

**Issue by IvanProdaiko94** [DATA-DOG/godog#164]
After bumping the version I started experiencing the issue during call
```
(exec godog --strict)
```

Error message:
```
failed to compile testmain package: exit status 2 - output: /var/folders/1k/bn5vg7sj1_x8k58ph3b4f9f80000gn/T/go-build058124600/b001/_testmain.go:4:2: can't find import: "github.com/DATA-DOG/godog"
```
 
I've got this error both in docker and locally.

**Comment by IvanProdaiko94** [comment]
Additional details:
OS: 
```OSX```
go version:
```
go version go1.11.5 darwin/amd64
```

**Comment by l3pp4rd** [comment]
Hi, there were changes in build process to support modules better. Is the source using modules or is in GOPATH. And is the godog package in vendor directory or in gopath?

**Comment by IvanProdaiko94** [comment]
I have `godog` types installed in `vendor` and use `GOPATH `.
Binary installed with `go get -u github.com/DATA-DOG/godog/cmd/godog`

**Comment by DiSiqueira** [comment]
Having the same error here

**Comment by l3pp4rd** [comment]
master should be fixed, could you try running: `go get -u github.com/DATA-DOG/godog/cmd/godog` again to update godog cli tool

**Comment by l3pp4rd** [comment]
reopen, in case if still experiencing issues, thanks

**Comment by thamizhv** [comment]
I recently installed godog using `GO111MODULE=on go get github.com/cucumber/godog/cmd/godog@v0.10.0` as mentioned in [README](https://github.com/cucumber/godog#install)

I got the error when I tried to run `godog` command on features folder

```
godog features/
failed to compile testmain package: exit status 2...
```
Checked all existing issues and tried a lot but no luck.
After several tries, ran the command with `sudo` and it ran successfully.

Mentioning here so it might be useful to someone facing similar issue.

Additional Details:
OS: macOS
Golang version:  go1.14.2 darwin/amd64
Godog version:  v0.10.0

**Comment by ivoaxi** [comment]
> After several tries, ran the command with `sudo` and it ran successfully.

Running sudo on `godog` nor `godog feature` did not help me. I still have the same error while having the same setup as you:

OS: macOS
go version go1.14.3 darwin/amd64
Godog version is: v0.10.0

**Comment by snargleplax** [comment]
Ran into a similar issue today. We had a `go.mod` file that had not been specifying a version number, which had been fine because we'd never consumed this module as a dependency. When we finally did so, we had to add an explicit version number to `go.mod` and update all our import paths. After merging in that change, I noticed that our `godog` runs started failing locally (but not failing on our CI server, which rotates in fresh build agents frequently). The error message was similar to that reported by the OP, except that the package it complains about not finding is our own package (no version number included in the error message) rather than the `godog` package.

I saw the note above about moving the module dir out of `GOPATH`, so I gave it a try and that worked right away. Still seems like a bug, though. We're not doing `go mod vendor` or anything. `sudo` didn't work.

Noted these related issues, but they didn't shed additional light: https://github.com/cucumber/godog/issues/136 https://github.com/cucumber/godog/issues/281

macOS
go version go1.14.7 darwin/amd64
Godog versions v0.09.0 and v0.10.0 (tried both)
